### ISSUE TITLE
Find a Security Scanning Tool that can output a SARIF file that can be ingested into Github's CodeQL

### ISSUE THREAD

**Issue by cbhernan** [CityOfLosAngeles/angeleno-account-my-account#14]

**Comment by cbhernan** [comment]
### Potential Solutions
semgrep [doesn't support Dart](https://semgrep.dev/docs/supported-languages/) as of now, though a January 2023 update [added **experimental** Dart support](https://semgrep.dev/docs/release-notes/january-2023/#semgrep-cli)

[Codecov](https://about.codecov.io/) - Free version - claims Dart support, but the application needs to be installed for the organization, I don't think there's a way to run locally 🤔 

[osv-scanner](https://github.com/google/osv-scanner) - Free - Uses https://osv.dev/ as database of vulnerability and scans pub packages; though not in their docs, they do [support SARIF outputs](https://github.com/google/osv-scanner/issues/216)

[SonarSource](https://www.sonarsource.com/knowledge/languages/) - Paid - no Dart support **/** [SonarQube](https://www.sonarsource.com/products/sonarqube/downloads/) has a community edition - doesn't list Dart, but will try to follow [this guide](https://dev.to/jamescardona11/flutter-code-static-analysis-with-sonarqube-3b39) and see what it can do. [_Edit: 8/31_: No SARIF output]

<hr/>

### Solutions Passed On
<sup>Due to no support or paid</sup>

[Veracode](https://www.veracode.com/products/binary-static-analysis-sast) - Paid - They **do support** [Dart & Flutter](https://docs.veracode.com/r/r_supported_table)

[Checkmarx](https://checkmarx.com/why-checkmarx/languages/) - Paid - [Does support Dart](https://checkmarx.com/resource/documents/en/34965-123552-supported-code-languages-and-frameworks-for-ep-9-5-2.html)

Synopsis has [Coverity](https://www.synopsys.com/software-integrity/security-testing/static-analysis-sast.html), which is a Paid service. [Don't think they support Dart](https://www.synopsys.com/software-integrity/security-testing/static-analysis-sast/languages-and-frameworks.html).

[Snyk](https://snyk.io/product/snyk-code/) - Free version - [no Dart support](https://docs.snyk.io/scan-application-code/supported-languages-and-frameworks)

[ContrastSecurity](https://www.contrastsecurity.com/security-agent) - Free version? - no Dart support

[Mend.io](https://www.mend.io/languages/) - Paid - no Dart support

Sonatype.com - No support

Gitlab.com - No support

Acunetix.com - No support

**Comment by jaylenw** [comment]
@cbhernan , based off of what you mentioned, osv-scanner could work to mark the requirement for SCA (Software Composition Analysis). Has their docs simply not been updated yet? I searched briefly into their GitHub issues for any DART support and no luck.

Noting @RV-LACity since the repository will be open source, I don't see a reason why we can't use CodeCov free SaaS offering if I understood correctly. It should not be a problem to install the app into our GitHub organization but we will need to figure out how we would manage it. @cbhernan if you think that Codecov will offer the best scanning capabilities out of any other solution we can look into it. Tangent, but there is a way to self-host codecov, there is a docker-compose.yml file they provide but we would just go with the free SaaS offering if it boils down to this.

Regarding Semgrep, it's experimental but we should explore it to help satisfy our requirement of having at least two SAST tools.

**Comment by jaylenw** [comment]
@RV-LACity  and I reviewed with @cbhernan  about the SASTS tooling listed as well as GitHub CodeQL and Trivy. Unfortunately, we are unable to find a tool that supports static application security scans for DART codebases. Semgrep says it is experimental but it is not in production. Codecov focuses on code coverage reporting but it seems like their is a product available for SAST. We are pretty sure that is a paid product.

@cbhernan  will look into testing Semgrep with the DART experimental ruleset for DART. If it is not available or valuable for us @RV-LACity and I agreed that we will put adding SAS for DART on hold until a supported and easily accessible tool gets released.

**Comment by jaylenw** [comment]
@cbhernan separate from this scope but we agree that SCA should still be done for DART packages.

**Comment by cbhernan** [comment]
@CityOfLosAngeles/ita-devsecops-team I found this potential SAST tool for DART - https://docs.horusec.io/docs/cli/analysis-tools/overview, would appreciate your thoughts!

**Comment by jaylenw** [comment]
> @CityOfLosAngeles/ita-devsecops-team I found this potential SAST tool for DART - https://docs.horusec.io/docs/cli/analysis-tools/overview, would appreciate your thoughts!

@cbhernan , let's try an implement this tool within GitHub Actions, https://docs.horusec.io/docs/cli/installation/#github-actions.

**Comment by cbhernan** [comment]
Closing this as we have OSV-Scanner checking our Pub packages for security issues and Dependabot and Semgrep for our Node code. Both contribute a SARIF file. Horusec is lower priority and nice to have since its capability seems limited.
