### ISSUE TITLE
Add Security Policies

### ISSUE THREAD

**Issue by cbhernan** [CityOfLosAngeles/angeleno-account-my-account#17]
### Problem
Nail down security policies and add `security.md` file to repository

### Resources
[Security file](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)

**Comment by technima** [comment]
To discuss with DevOps: Should we tie this in or reference ISO's vulnerability disclosure program?

**Comment by technima** [comment]
@cbhernan I'm reopening this so you can answer my previous comment on here.

**Comment by cbhernan** [comment]
@technima Sorry about that. Discussing with @jaylenw now and will open supplemental PR if needed.

**Comment by jaylenw** [comment]
@cbhernan and @technima , I had mentioned this with ISO before on a general level for repositories within our org. Specifically, having in our `SECURITY.md` files mention that security issues should be submitted to our vulnerability disclosure program. However, if I recall correctly a VDP is the goal but our current setup with Hackerone is not configured for this nor we have the funding for a proper VDP. I would consult with @jaimeh1  on this as I could be wrong / out of date on the details.

For this particular case, as mentioned in https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/pull/20#pullrequestreview-1583586683 the `SECURITY.md` file should contain instructions for users to use the repo's private vulnerability reporting functionality as far as my team is concerned.

Not related to the `SECURITY.md` file specifically, but related to security, we have an internal policy that states "...[team] expects to make a new release that fixes a high or critical security vulnerability within the timeframe of two weeks from the time we were first notified about the vulnerability." This is something you guys should consider and aim for. We talked to security team about this a long time ago so please get their input. If I can think of anything else that we had not already discussed I'll let y'all know.

**Comment by cbhernan** [comment]
[SNow Incident](https://cityoflaprod.service-now.com/nav_to.do?uri=incident.do?sys_id=c4bc0b108711b950be0ea71e0ebb35ca) for discussion around ISO VDP
