### ISSUE TITLE
Integrate Auth0 and Login Tab for Testing

### ISSUE THREAD

**Issue by Paz-X** [CityOfLosAngeles/angeleno-account-my-account#33]

**Comment by Paz-X** [comment]
-Also adding the following fixes:
   -The small screen unselectedcolor was defaulting to white, made them grey
   -Added greycolor to constants

**Comment by nickchaula** [comment]
No longer implementing login tab

**Comment by nickchaula** [comment]
No longer implementing login tab

**Comment by nickchaula** [comment]
No longer implementing login tab
