### ISSUE TITLE
Email Verification in Auth0

### ISSUE THREAD

**Issue by cbhernan** [CityOfLosAngeles/angeleno-account-my-account#64]
### Problem
Users can currently sign up to our Auth0 tenant using any email, this creates a problem as the email is not verified before adding to the database, so when the actual user with the email tries to sign up they won't be allowed because their email will already exist in database.

### Proposed Solution
We need to find a way to verify the user's email, and create a job that will remove any emails that are not verified within a certain time.

### Resources
https://community.auth0.com/t/how-to-deal-with-unverified-users/91808
https://community.auth0.com/t/how-to-clean-up-stale-accounts/86420/3

**Comment by cbhernan** [comment]
Require Email Verification Auth0 Action in Login Flow

<img width="302" alt="Screenshot 2023-12-06 112638" src="https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/assets/6743989/18867265-cbd8-4ec9-84bf-89beec49bbe7">

**Comment by nickchaula** [comment]
Email verification being done, issue being handled on Auth0 config repo
