### ISSUE TITLE
Update ReadMe - Add introduction, update deployment section

### ISSUE THREAD

**Issue by cbhernan** [CityOfLosAngeles/angeleno-account-my-account#76]
- [x] Rename Angeleno - Profile to Angeleno - My Account
- [x] Provide introduction as to what the My Account is/does
- [x] Update development and deployment instructions

**Comment by Paz-X** [comment]
Updated readme and a PR: https://github.com/CityOfLosAngeles/angeleno-my-account/pull/83

**Comment by Paz-X** [comment]
Updated as of 4.15.2024. Review needed to close this out.
